version: "3.8"

services:
  web:
    build: ./flask-api
    command: gunicorn --bind 0.0.0.0:5000 main
    container_name: flask
    ports:
      - 5000:5000

    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4

    environment:
      MONGODB_DATA_DIR: /data/db
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mongoseed
    links:
      - mongodb

volumes:
  mongodbdata:
